#Limpeza e Tratamento das Tabelas

In [1]:
import pandas as pd
df_games = pd.read_csv('games.csv')
df_platforms = pd.read_csv('platform_summary.csv')

##Tratamento da tabela Platform

In [2]:
df_platforms = pd.read_csv('platform_summary.csv')
df_platforms.reset_index(inplace=True)
df_games['platform'] = df_games['platform'].map(df_platforms.set_index('platform')['index'])

df_games = df_games.drop(columns=['platform_type','platform_maker','platform_generation'])

Criação e tratamento da tabela Sales

In [9]:
df_sales = pd.DataFrame()
colunas_desejadas = ['game_id','na_sales_million','eu_sales_million','jp_sales_million','other_sales_million','global_sales_million','estimated_revenue_million_usd']
df_sales= df_games[colunas_desejadas].copy()

In [10]:
df_sales.head()

,game_id,na_sales_million,eu_sales_million,jp_sales_million,other_sales_million,global_sales_million,estimated_revenue_million_usd
0,G000001,10.01,8.35,2.58,3.46,24.40,575.88
1,G000002,52.28,33.72,5.32,12.30,103.62,5056.51
2,G000003,2.90,1.48,0.75,0.91,6.04,138.60
3,G000004,6.76,3.27,0.73,2.34,13.10,36.98
4,G000005,25.12,15.94,7.02,7.71,55.79,2148.24

In [16]:
df_games = df_games.drop(columns= colunas_desejadas)

In [28]:
top10_jogos = pd.merge(df_games,df_sales,on="game_id")
top10_jogos = top10_jogos.nlargest(10,"global_sales_million")
top10_jogos.head()

,game_id,title,platform,genre,year,publisher,developer,publisher_region,publisher_tier,esrb_rating,...,goty_nominated,goty_won,how_long_to_beat_main_hrs,how_long_to_beat_completionist_hrs,na_sales_million,eu_sales_million,jp_sales_million,other_sales_million,global_sales_million,estimated_revenue_million_usd
17200,G017201,NHL 2025,7,Sports,2012,Take-Two Interactive,Take-Two Interactive,USA,AAA,E,...,0,0,15.4,49.6,769.07,365.09,59.96,300.56,1494.68,2970.64
414,G000415,Devil May Cry,7,Action,2015,Activision Blizzard,Activision Blizzard,USA,AAA,M,...,1,0,12.8,55.7,687.54,344.93,203.31,171.88,1407.66,4008.39
4510,G004511,Valheim : Redux,7,Sandbox,2018,Nintendo,Rockstar Games,Japan,AAA,E,...,0,0,156.6,497.0,545.13,389.10,165.27,180.12,1279.62,2974.11
5352,G005353,Terraria Legacy,8,Sandbox,2021,Electronic Arts,Electronic Arts,USA,AAA,M,...,1,1,151.7,712.5,594.28,347.96,101.33,114.38,1157.95,3010.49
38695,G038696,Roblox 2,32,Sandbox,2024,Activision Blizzard,Activision Blizzard,USA,AAA,T,...,0,0,207.6,788.4,543.94,297.07,49.21,132.12,1022.34,45483.54